// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"fmt"

	"github.com/go-faster/errors"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/bad_gateway_error
type BadGatewayError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadGatewayError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadGatewayError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadGatewayError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadGatewayError) SetMessage(val string) {
	s.Message = val
}

func (*BadGatewayError) cancelOrderRes()    {}
func (*BadGatewayError) createOrderRes()    {}
func (*BadGatewayError) getOrderByUUIDRes() {}
func (*BadGatewayError) payOrderRes()       {}

// Ref: #/components/schemas/bad_request_error
type BadRequestError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val string) {
	s.Message = val
}

func (*BadRequestError) cancelOrderRes()    {}
func (*BadRequestError) createOrderRes()    {}
func (*BadRequestError) getOrderByUUIDRes() {}
func (*BadRequestError) payOrderRes()       {}

// CancelOrderNoContent is response for CancelOrder operation.
type CancelOrderNoContent struct{}

func (*CancelOrderNoContent) cancelOrderRes() {}

// Ref: #/components/schemas/conflict_error
type ConflictError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ConflictError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ConflictError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val string) {
	s.Message = val
}

func (*ConflictError) cancelOrderRes() {}

// Ref: #/components/schemas/create_order_request
type CreateOrderRequest struct {
	// Уникальный идентификатор пользователя, создающего
	// заказ.
	UserUUID string `json:"user_uuid"`
	// Список уникальных идентификаторов частей,
	// включенных в заказ.
	PartUuids []string `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() string {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []string {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val string) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []string) {
	s.PartUuids = val
}

// Ref: #/components/schemas/create_order_response
type CreateOrderResponse struct {
	// Уникальный идентификатор созданного заказа.
	OrderUUID OptString `json:"order_uuid"`
	// Общая стоимость созданного заказа.
	TotalPrice OptFloat64 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() OptString {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() OptFloat64 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val OptString) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val OptFloat64) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) createOrderRes() {}

// Ref: #/components/schemas/forbidden_error
type ForbiddenError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ForbiddenError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ForbiddenError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ForbiddenError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ForbiddenError) SetMessage(val string) {
	s.Message = val
}

func (*ForbiddenError) cancelOrderRes()    {}
func (*ForbiddenError) createOrderRes()    {}
func (*ForbiddenError) getOrderByUUIDRes() {}
func (*ForbiddenError) payOrderRes()       {}

// Ref: #/components/schemas/generic_error
type GenericError struct {
	// HTTP-код ошибки.
	Code OptInt `json:"code"`
	// Описание ошибки.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val OptString) {
	s.Message = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

// Ref: #/components/schemas/get_order_response
type GetOrderResponse struct {
	// Уникальный идентификатор заказа.
	OrderUUID string `json:"order_uuid"`
	// Уникальный идентификатор пользователя, сделавшего
	// заказ.
	UserUUID string `json:"user_uuid"`
	// Список уникальных идентификаторов частей,
	// включенных в заказ.
	PartUuids []string `json:"part_uuids"`
	// Общая стоимость заказа.
	TotalPrice float64 `json:"total_price"`
	// Уникальный идентификатор транзакции, связанный с
	// заказом.
	TransactionUUID OptString        `json:"transaction_uuid"`
	PaymentMethod   OptPaymentMethod `json:"payment_method"`
	Status          OrderStatus      `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *GetOrderResponse) GetOrderUUID() string {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *GetOrderResponse) GetUserUUID() string {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *GetOrderResponse) GetPartUuids() []string {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *GetOrderResponse) GetTotalPrice() float64 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *GetOrderResponse) GetTransactionUUID() OptString {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *GetOrderResponse) GetPaymentMethod() OptPaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *GetOrderResponse) GetStatus() OrderStatus {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *GetOrderResponse) SetOrderUUID(val string) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *GetOrderResponse) SetUserUUID(val string) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *GetOrderResponse) SetPartUuids(val []string) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *GetOrderResponse) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *GetOrderResponse) SetTransactionUUID(val OptString) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *GetOrderResponse) SetPaymentMethod(val OptPaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *GetOrderResponse) SetStatus(val OrderStatus) {
	s.Status = val
}

func (*GetOrderResponse) getOrderByUUIDRes() {}

// Ref: #/components/schemas/internal_server_error
type InternalServerError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerError) cancelOrderRes()    {}
func (*InternalServerError) createOrderRes()    {}
func (*InternalServerError) getOrderByUUIDRes() {}
func (*InternalServerError) payOrderRes()       {}

// Ref: #/components/schemas/not_found_error
type NotFoundError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) cancelOrderRes()    {}
func (*NotFoundError) getOrderByUUIDRes() {}
func (*NotFoundError) payOrderRes()       {}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentMethod returns new OptPaymentMethod with value set to v.
func NewOptPaymentMethod(v PaymentMethod) OptPaymentMethod {
	return OptPaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptPaymentMethod is optional PaymentMethod.
type OptPaymentMethod struct {
	Value PaymentMethod
	Set   bool
}

// IsSet returns true if OptPaymentMethod was set.
func (o OptPaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentMethod) Reset() {
	var v PaymentMethod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentMethod) SetTo(v PaymentMethod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentMethod) Get() (v PaymentMethod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentMethod) Or(d PaymentMethod) PaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Статус заказа.
// Ref: #/components/schemas/order_status
type OrderStatus string

const (
	OrderStatusPENDINGPAYMENT OrderStatus = "PENDING_PAYMENT"
	OrderStatusPAID           OrderStatus = "PAID"
	OrderStatusCANCELLED      OrderStatus = "CANCELLED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusPENDINGPAYMENT,
		OrderStatusPAID,
		OrderStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusPENDINGPAYMENT:
		return []byte(s), nil
	case OrderStatusPAID:
		return []byte(s), nil
	case OrderStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusPENDINGPAYMENT:
		*s = OrderStatusPENDINGPAYMENT
		return nil
	case OrderStatusPAID:
		*s = OrderStatusPAID
		return nil
	case OrderStatusCANCELLED:
		*s = OrderStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/pay_order_request
type PayOrderRequest struct {
	PaymentMethod OptPaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() OptPaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val OptPaymentMethod) {
	s.PaymentMethod = val
}

// Ref: #/components/schemas/pay_order_response
type PayOrderResponse struct {
	// Уникальный идентификатор транзакции, связанный с
	// оплатой заказа.
	TransactionUUID OptString `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderResponse) GetTransactionUUID() OptString {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderResponse) SetTransactionUUID(val OptString) {
	s.TransactionUUID = val
}

func (*PayOrderResponse) payOrderRes() {}

// Метод оплаты.
// Ref: #/components/schemas/payment_method
type PaymentMethod string

const (
	PaymentMethodPAYMENTMETHODUNKNOWN       PaymentMethod = "PAYMENT_METHOD_UNKNOWN"
	PaymentMethodPAYMENTMETHODCARD          PaymentMethod = "PAYMENT_METHOD_CARD"
	PaymentMethodPAYMENTMETHODSBP           PaymentMethod = "PAYMENT_METHOD_SBP"
	PaymentMethodPAYMENTMETHODCREDITCARD    PaymentMethod = "PAYMENT_METHOD_CREDIT_CARD"
	PaymentMethodPAYMENTMETHODINVESTORMONEY PaymentMethod = "PAYMENT_METHOD_INVESTOR_MONEY"
)

// AllValues returns all PaymentMethod values.
func (PaymentMethod) AllValues() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodPAYMENTMETHODUNKNOWN,
		PaymentMethodPAYMENTMETHODCARD,
		PaymentMethodPAYMENTMETHODSBP,
		PaymentMethodPAYMENTMETHODCREDITCARD,
		PaymentMethodPAYMENTMETHODINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PaymentMethodPAYMENTMETHODUNKNOWN:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODCARD:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODSBP:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODCREDITCARD:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentMethod) UnmarshalText(data []byte) error {
	switch PaymentMethod(data) {
	case PaymentMethodPAYMENTMETHODUNKNOWN:
		*s = PaymentMethodPAYMENTMETHODUNKNOWN
		return nil
	case PaymentMethodPAYMENTMETHODCARD:
		*s = PaymentMethodPAYMENTMETHODCARD
		return nil
	case PaymentMethodPAYMENTMETHODSBP:
		*s = PaymentMethodPAYMENTMETHODSBP
		return nil
	case PaymentMethodPAYMENTMETHODCREDITCARD:
		*s = PaymentMethodPAYMENTMETHODCREDITCARD
		return nil
	case PaymentMethodPAYMENTMETHODINVESTORMONEY:
		*s = PaymentMethodPAYMENTMETHODINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/rate_limit_error
type RateLimitError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *RateLimitError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *RateLimitError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *RateLimitError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *RateLimitError) SetMessage(val string) {
	s.Message = val
}

func (*RateLimitError) cancelOrderRes()    {}
func (*RateLimitError) createOrderRes()    {}
func (*RateLimitError) getOrderByUUIDRes() {}
func (*RateLimitError) payOrderRes()       {}

// Ref: #/components/schemas/service_unavailable_error
type ServiceUnavailableError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ServiceUnavailableError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ServiceUnavailableError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ServiceUnavailableError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ServiceUnavailableError) SetMessage(val string) {
	s.Message = val
}

func (*ServiceUnavailableError) cancelOrderRes()    {}
func (*ServiceUnavailableError) createOrderRes()    {}
func (*ServiceUnavailableError) getOrderByUUIDRes() {}
func (*ServiceUnavailableError) payOrderRes()       {}

// Ref: #/components/schemas/unauthorized_error
type UnauthorizedError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *UnauthorizedError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *UnauthorizedError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *UnauthorizedError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *UnauthorizedError) SetMessage(val string) {
	s.Message = val
}

func (*UnauthorizedError) cancelOrderRes()    {}
func (*UnauthorizedError) createOrderRes()    {}
func (*UnauthorizedError) getOrderByUUIDRes() {}
func (*UnauthorizedError) payOrderRes()       {}

// Ref: #/components/schemas/validation_error
type ValidationError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ValidationError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ValidationError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ValidationError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ValidationError) SetMessage(val string) {
	s.Message = val
}

func (*ValidationError) cancelOrderRes()    {}
func (*ValidationError) createOrderRes()    {}
func (*ValidationError) getOrderByUUIDRes() {}
func (*ValidationError) payOrderRes()       {}
